name: Rebuild Cookbook Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Hook
        run: curl -X POST ${{ secrets.WEBSITE_DEPLOY_HOOK_URL }}
